name: client
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  dio: ^5.8.0+1
  intl: ^0.20.2
  logger: ^2.5.0
  flutter_dotenv: ^5.2.1
  font_awesome_flutter: ^10.8.0
  file_picker: ^10.2.0
  supabase_flutter: ^2.9.1
  delightful_toast: ^1.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.5.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
